#include "sensor_id_util.h"
#include "sensor_class.h"
#include "sensor_id.h"


// 센서 종류, 정상값 저장
SensorClass sensor_classes[] =
{
    // Bond Head
    {MAKE_CLASS_ID(MODULE_BOND_HEAD, SENSOR_TEMPERATURE),        60.0, 150.0},
    {MAKE_CLASS_ID(MODULE_BOND_HEAD, SENSOR_FORCE),               0.2,   5.0},
    {MAKE_CLASS_ID(MODULE_BOND_HEAD, SENSOR_ULTRASONIC_POWER),    0.5,   5.0},
    {MAKE_CLASS_ID(MODULE_BOND_HEAD, SENSOR_VIBRATION),           0.0,   0.3},

    // Stage
    {MAKE_CLASS_ID(MODULE_STAGE, SENSOR_POSITION_ENCODER),        0.0, 300.0},
    {MAKE_CLASS_ID(MODULE_STAGE, SENSOR_MOTOR_CURRENT),           0.2,   2.5},
    {MAKE_CLASS_ID(MODULE_STAGE, SENSOR_MOTOR_VOLTAGE),          24.0,  48.0},
    {MAKE_CLASS_ID(MODULE_STAGE, SENSOR_MOTOR_SPEED),             0.0, 500.0},
    {MAKE_CLASS_ID(MODULE_STAGE, SENSOR_VIBRATION),               0.0,   0.2},

    // Heater
    {MAKE_CLASS_ID(MODULE_HEATER, SENSOR_TEMPERATURE),          100.0, 250.0},
    {MAKE_CLASS_ID(MODULE_HEATER, SENSOR_POWER_CONSUMPTION),    200.0,1000.0},

    // Vacuum
    {MAKE_CLASS_ID(MODULE_VACUUM, SENSOR_VACUUM_PRESSURE),      -80.0, -30.0},
    {MAKE_CLASS_ID(MODULE_VACUUM, SENSOR_FLOW),                   5.0,  50.0},

    // Motor / Drive
    {MAKE_CLASS_ID(MODULE_MOTOR_DRIVE, SENSOR_MOTOR_CURRENT),     0.5,   5.0},
    {MAKE_CLASS_ID(MODULE_MOTOR_DRIVE, SENSOR_MOTOR_VOLTAGE),    24.0,  48.0},
    {MAKE_CLASS_ID(MODULE_MOTOR_DRIVE, SENSOR_MOTOR_SPEED),       0.0,3000.0},
    {MAKE_CLASS_ID(MODULE_MOTOR_DRIVE, SENSOR_VIBRATION),         0.0,   0.4},

    // Vision
    {MAKE_CLASS_ID(MODULE_VISION, SENSOR_VISION_ALIGNMENT),      -5.0,   5.0},
    {MAKE_CLASS_ID(MODULE_VISION, SENSOR_DEFECT_DETECTION),       0.0,   1.0},

    // Environment
    {MAKE_CLASS_ID(MODULE_ENVIRONMENT, SENSOR_TEMPERATURE),      20.0,  25.0},
    {MAKE_CLASS_ID(MODULE_ENVIRONMENT, SENSOR_HUMIDITY),         30.0,  50.0},
    {MAKE_CLASS_ID(MODULE_ENVIRONMENT, SENSOR_AIRFLOW),           0.3,   1.0},

    // Power
    {MAKE_CLASS_ID(MODULE_POWER, SENSOR_POWER_CONSUMPTION),    2000.0,10000.0}
};


// 실제 메모리 할당 + 초기화
const int SENSOR_CLASS_COUNT = sizeof(sensor_classes) / sizeof(SensorClass);